services:
  api:
    build:
      context: .
    image: ivanglie/coinmon-api:latest
    container_name: coinmon-api
    restart: always
    networks:
      - internal

  proxy:
    image: caddy:latest
    container_name: coinmon-proxy
    ports:
      - "80:80"
    command: caddy reverse-proxy --from :80 --to api:8080
    depends_on:
      - api
    networks:
      - internal

networks:
  internal:
    driver: bridge